#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Cluster"})
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
spec:
  topology:
    class: tkg-vsphere-default-v1.2.0-extended
    variables:
    - name: encryptionKey
      value: "7dwUtOMdt+6IO8cZwJhO0HzZuEm1zeiw+s18FOEwD1U="
